name       : roct-thunk-interface
version    : 4.0.0
release    : 2
source     :
    - https://github.com/RadeonOpenCompute/ROCT-Thunk-Interface/archive/rocm-4.0.0.tar.gz : a6960fffc8388731ee18953faae12d1449c582e3b3594418845a544455895f42
homepage   : https://github.com/RadeonOpenCompute/ROCT-Thunk-Interface
license    :
    - BSD-2-Clause
    - MIT
component  : programming.devel
summary    : Radeon Open Compute Thunk Interface
description: |
    This repository includes the user-mode API interfaces used to interact with the ROCk driver. Currently supported agents include only the AMD/ATI Fiji family of discrete GPUs.
builddeps  :
    - pkgconfig(libpci)
    - pkgconfig(numa)
setup      : |
    %cmake_ninja -DCMAKE_BUILD_TYPE=Release ..
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc
